### ISSUE TITLE
Language inconsistency and vague naming schemes

### ISSUE THREAD

**Issue by jonay2000** [HuskyNator/ProjectGiraffe#1]
![image](https://user-images.githubusercontent.com/22172241/62548754-96a44100-b867-11e9-832c-a92527dd226d.png)
![image](https://user-images.githubusercontent.com/22172241/62548782-a459c680-b867-11e9-88cc-375b7383aeae.png)
![image](https://user-images.githubusercontent.com/22172241/62548795-ade32e80-b867-11e9-88ba-0ef6cb2a6236.png)
![image](https://user-images.githubusercontent.com/22172241/62548965-f26eca00-b867-11e9-974e-d8aacaed94e2.png)

"exceptions" written in lower case English while "Wereld" is written in uppercase Dutch. Readme written in English while code (in an English-focused language) has a Dutch naming scheme.
Commit messages both in Dutch and English.

As you are using a programming language that is English-focused, I recommend you try to stick to English naming conventions.

**Comment by HuskyNator** [comment]
Haha, had dit niet verwacht.
Overigens ben ik van plan de hele folder te verwijderen.
